spring:
  cloud:
    gateway:
      routes:
      - id: Accounts
        uri: lb://ACCOUNTS
        predicates:
        - Path=/account/**
        
      - id: Coupons
        uri: lb://COUPONS
        filters:
          - JwtFilter
        predicates:
        - Path=/coupon/**
        
      - id: Orders
        uri: lb://ORDERS
        filters:
           - JwtFilter
        predicates:
        - Path=/order/**
        
      - id: Products
        uri: lb://Products
        filters:
          - JwtFilter
        predicates:
        - Path=/product/**
        
jwt:
    secret-key: coupon-management      
