spring:
  cloud:
    gateway:
      routes:
      - id: Accounts
        uri: http://localhost:8081/
        predicates:
        - Path=/account/**
      - id: Coupons
        uri: http://localhost:8082/
        predicates:
        - Path=/coupon/**
      - id: Orders
        uri: http://localhost:8083/
        predicates:
        - Path=/order/**